language: r
cache: packages

r_github_packages:
  - jtextor/epitope-prediction
  - richelbilderbeek/epiprepreds
  - richelbilderbeek/beautier
  - richelbilderbeek/beastier
  - ropensci/mcbette
  - thijsjanzen/nodeSub
  - richelbilderbeek/pirouette
  - richelbilderbeek/peregrine
  - richelbilderbeek/beastier
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/tmhmm
  - richelbilderbeek/mhcnuggetsr
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/nmhc2ppreds
  - richelbilderbeek/bbbq

bioc_packages:
  - msa

before_install:
  # Fix rJava error, from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
  - sudo $(which R) CMD javareconf
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
 
after_install:
  - sudo apt install r-cran-testthat r-cran-stringr r-cran-dplyr r-cran-readr r-cran-knitr r-cran-rcpp

before_script:
  - sudo apt install tcsh
  - Rscript -e 'mhcnuggetsr::install_mhcnuggets()'
  - Rscript -e 'pureseqtmr::install_pureseqtm()'
  - Rscript -e 'if (netmhc2pan::is_url_valid()) netmhc2pan::install_netmhc2pan()'

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz
  - ./test.sh
  - if [ ! -f fig_f_tmh_mhc2_grid.png ]; then echo "file 'fig_f_tmh_mhc2_grid.png' not found" ; exit 1 ; fi

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

