language: r
# dist: bionic # Uncomment until fix of https://travis-ci.community/t/r-install-broken-travis-ci-rstudio-org-returns-403/9640
cache: packages

r_github_packages:
  - jtextor/epitope-prediction
  - richelbilderbeek/epiprepreds
  - richelbilderbeek/mcbette
  - thijsjanzen/nodeSub
  - richelbilderbeek/pirouette
  - richelbilderbeek/peregrine
  - richelbilderbeek/beastier
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/mhcnuggetsr
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/nmhc2ppreds
  - richelbilderbeek/bbbq

before_install:
  # From https://stackoverflow.com/a/20042195
  - Rscript -e "update.packages(checkBuilt = TRUE, ask = FALSE)"
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
 
after_install:
  - sudo apt install r-cran-testthat r-cran-stringr r-cran-dplyr r-cran-readr r-cran-knitr r-cran-rcpp

before_script:
  - sudo apt install tcsh
  - Rscript -e 'mhcnuggetsr::install_mhcnuggets()'
  - Rscript -e 'pureseqtmr::install_pureseqtm()'
  - Rscript -e 'netmhc2pan::install_netmhc2pan()'

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz
  - Rscript -e 'mhcnuggetsr::install_mhcnuggets()'
  - Rscript -e 'pureseqtmr::install_pureseqtm()'
  - ./test.sh
  - if [ ! -f fig_f_tmh_mhc2_grid.png ]; then echo "file 'fig_f_tmh_mhc2_grid.png' not found" ; exit 1 ; fi

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'

after_failure:
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - Rscript -e 'pureseqtmr::pureseqtmr_report()'

